Fixed many bugs, ensure features working as intended.
Everything changed. Breaking changes everywhere. But getting closer to a stable place

diff --git a/scripts/setupRemoteTests b/scripts/setupRemoteTests
--- a/scripts/setupRemoteTests
+++ b/scripts/setupRemoteTests
@@ -2,20 +2,20 @@
 
 set +e
 
-if [[ "$0" == "$BASH_SOURCE" ]]; then
+if [[ "$0" == "${BASH_SOURCE[0]}" ]]; then
     echo "ERR setupRemoteTests must be sourced, not executed. Try:"
     echo "source ./scripts/setupRemoteTests"
     exit 1
 fi
 
 if [[ ! -e ./scripts ]]; then
-  echo "ERR Could not find ./scripts directory, are you at the root of the repo? i.e. ~/repos/weblens and not ~/repos/weblens/scripts"
-  return 1
+    echo "ERR Could not find ./scripts directory, are you at the root of the repo? i.e. ~/repos/weblens and not ~/repos/weblens/scripts"
+    return 1
 fi
 
-printf "Killing other instances of Weblens... "
-pkill weblens &> /dev/null || true
-printf "Done\n"
+# printf "Killing other instances of Weblens... "
+# pkill weblens &>/dev/null || true
+# printf "Done\n"
 
 export APP_ROOT=$PWD
 
@@ -23,86 +23,97 @@ mkdir -p ./build/bin
 rm -f ./build/bin/weblens
 
 mkdir -p ./build/logs/
-
-printf "Compiling Weblens... "
-if ! go build -v -race -o ./build/bin/weblens ./cmd/weblens/main.go &> ./build/logs/compile-mock-core.log; then
-  printf "\n"
-  echo "###########################################################################################"
-  cat ./build/logs/compile-mock-core.log
-  echo "###################################### ^ Compile Logs ^ ###################################"
-  echo "ERR Returned non-0 exit status, exiting..."
-  return 1
-fi
-printf "Done\n"
-
 mkdir -p ./build/core-test
 mkdir -p ./build/backup-test
 
 printf "Dropping old databases... "
-mongosh --eval "use weblens-mock-core" --eval "db.dropDatabase()" > /dev/null
-#mongosh --eval "use weblens-backup-test" --eval "db.dropDatabase()" > /dev/null
+mongosh --eval "use weblens-mock-core" --eval "db.dropDatabase()" >/dev/null
 printf "Done\n"
 
-CONFIG_NAME=MOCK-CORE ./build/bin/weblens &> ./build/logs/core-test-target.log &
-printf "Launched core process\n"
+dataRoot=$(jq -r '.["MOCK-CORE"].["dataRoot"]' <./config/config.json)
+cachesRoot=$(jq -r '.["MOCK-CORE"].["cachesRoot"]' <./config/config.json)
+rm -rf "$dataRoot"
+rm -rf "$cachesRoot"
 
-function wait_for_startup () {
-  printf "Waiting up to 10s for Weblens startup... "
-  counter=0
-  while [ "$(curl -s --location 'http://localhost:8089/api/info' 2> /dev/null | jq '.started')" != "true" ]
-  do
-    sleep 1
-    ((counter++))
-    if [ "$counter" -ge "10" ]; then
-      printf "\n"
-      echo "###########################################################################################"
-      cat ./build/logs/core-test-target.log
-      echo "###################################### ^ Core Logs ^ ######################################"
-      echo "ERR Failed to connect to weblens core after 10 seconds, exiting..."
-      return 1
-    fi
-  done
-  printf "Connected\n"
+printf "\n### Starting Weblens Core ###\n"
+if ! ./scripts/startWeblens --trace --config MOCK-CORE -d --log ./build/logs/core-test-target.log; then
+    printf "\n### FAILED ###\n"
+    return 1
+fi
+printf "### Core Started ###\n\n"
+
+function wait_for_startup() {
+    printf "Waiting up to 10s for Weblens startup... "
+    counter=0
+    while [ "$(curl -s --location 'http://localhost:8089/api/info' 2>/dev/null | jq '.started')" != "true" ]; do
+        sleep 1
+        ((counter++))
+        if [ "$counter" -ge "10" ]; then
+            printf "\n"
+            echo "###########################################################################################"
+            cat ./build/logs/core-test-target.log
+            echo "###################################### ^ Core Logs ^ ######################################"
+            echo "ERR Failed to connect to weblens core after 10 seconds, exiting..."
+            return 1
+        fi
+    done
+    printf "Connected\n"
 }
 
 wait_for_startup
 
+testUserName="test-user"
+
 printf "Initializing core server... "
-serverId=$(curl --location 'http://localhost:8089/api/init' \
---header 'Content-Type: application/json' \
---data '{
-    "name": "MOCK-CORE",
-    "role": "core",
-    "username": "ethan",
-    "password": "password"
-}' 2> /dev/null | jq -r '.id')
+serverResponse=$(curl --location 'http://localhost:8089/api/servers/init' \
+    --header 'Content-Type: application/json' \
+    --data "{
+    \"name\": \"MOCK-CORE\",
+    \"role\": \"core\",
+    \"username\": \"$testUserName\",
+    \"password\": \"password\"
+}" 2>/dev/null)
+
+serverId=$(echo "$serverResponse" | jq -r '.id')
+
+if [[ "$serverId" == "" ]]; then
+    printf "FAILED\n"
+    echo "ERR Failed Initializing server, exiting..."
+    echo "$serverResponse"
+    return 1
+fi
 printf "Done\n"
 
 wait_for_startup
 
 printf "Logging in new user... "
-token=$(curl --location 'http://localhost:8089/api/login' \
-        --header 'Content-Type: application/json' \
-        --data '{
-            "username": "ethan",
-            "password": "password"
-        }' 2> /dev/null | jq -r '.token')
+loginResponse=$(curl --location 'http://localhost:8089/api/users/auth' \
+    --header 'Content-Type: application/json' \
+    --data "{
+            \"username\": \"$testUserName\",
+            \"password\": \"password\"
+        }" 2>/dev/null)
 
-if [[ "$token" == "" ]]; then
-  printf "FAILED\n"
-  echo "ERR Failed to login user, exiting..."
-  return 1
+token=$(jq -r '.token' <<<"$loginResponse")
+
+if [[ "$token" == "" ]] || [[ "$token" == "null" ]]; then
+    printf "FAILED\n"
+    echo "ERR Failed to login user, exiting..."
+    echo "$loginResponse"
+    return 1
 fi
 
 printf "Done\n"
 
 printf "Generating API Key... "
-apiKey=$(curl --location --request POST 'http://localhost:8089/api/key' --cookie "weblens-session-token=$token" 2> /dev/null | jq -r '.key."key"')
+apiKeyResponse=$(curl --request POST --location 'http://localhost:8089/api/keys' --cookie "weblens-session-token=$token" 2>/dev/null)
+apiKey=$(jq -r '.key' <<<"$apiKeyResponse")
 
 if [[ "$apiKey" == "" ]]; then
-  printf "FAILED\n"
-  echo "ERR Did not get API key from core server, exiting..."
-  return 1
+    printf "FAILED\n"
+    echo "ERR Did not get API key from core server, exiting..."
+    echo "$apiKeyResponse"
+    return 1
 fi
 printf "Done\n"
 
diff --git a/scripts/startWeblens b/scripts/startWeblens
--- a/scripts/startWeblens
+++ b/scripts/startWeblens
@@ -1,52 +1,146 @@
 #!/bin/bash
 
 if [[ ! -e ./cmd ]]; then
-  echo "ERR Could not find ./cmd directory, are you at the root of the repo? i.e. ~/repos/weblens and not ~/repos/weblens/scripts"
-  exit 1
+	echo "ERR Could not find ./cmd directory, are you at the root of the repo? i.e. ~/repos/weblens and not ~/repos/weblens/scripts"
+	exit 1
 fi
 
-if [[ ! -e ./build/bin ]]; then
-  mkdir -p ./build/bin
-fi
+mkdir -p ./build/bin
+mkdir -p ./build/logs
 
 restart=false
+trace=false
+docs=false
+detach=false
+build_ui=false
+log_file="$WEBLENS_LOG_FILE"
+config_name="$CONFIG_NAME"
 
-while getopts "r" opt; do
-  case $opt in
-    r) restart=true
-    ;;
-    \?) echo "Invalid option -$OPTARG" >&2
-    exit 1
-    ;;
-  esac
-
-  case $OPTARG in
-    -*) echo "Option $opt needs a valid argument"
-    exit 1
-    ;;
-  esac
+while [ "${1:-}" != "" ]; do
+	case "$1" in
+	"--config")
+		shift
+		config_name=$1
+		;;
+	"--log")
+		shift
+		log_file=$1
+		;;
+	"-t" | "--trace")
+		trace=true
+		;;
+	"--ui")
+		build_ui=true
+		;;
+	"-r" | "--restart")
+		restart=true
+		;;
+	"--docs")
+		docs=true
+		;;
+	"-d" | "--detach")
+		detach=true
+		;;
+	esac
+	shift
 done
+
+if [[ $detach == true ]] && [[ -z "$log_file" ]]; then
+	echo "ERR --detach requires --log to be set"
+	exit 1
+fi
+
+if [[ -z "$config_name" ]]; then
+	export config_name="DEBUG-CORE"
+fi
+
+printf "Using config: %s" "$config_name"
+if [[ $trace == true ]]; then
+	export LOG_LEVEL="trace"
+	printf " +trace"
+fi
+printf "\n"
+
+# Allow for easy restarts while debugging. If you send a SIGQUIT (Ctrl+\),
+# it will re[build/start] the server when $restart is true (cmd line option -r).
+trap "" SIGQUIT
 
 while true; do
-  rm -f ./build/bin/weblens
+	if [[ $docs == true ]]; then
+		printf "Building Docs..."
+		if ! ./scripts/swaggo &>./build/logs/docs-build.log; then
+			printf " FAILED\n"
+			cat ./build/logs/docs-build.log
+			echo "Aborting Weblens startup. Failed to build docs"
+			exit 1
+		else
+			printf " DONE\n"
+		fi
 
-  go build -gcflags="-N -l" -race -o ./build/bin/weblens ./cmd/weblens/main.go
+	fi
 
-  if [[ ! -e ./build/bin/weblens ]]; then
-    echo "Failed to build Weblens, exiting..."
-    exit 1
-  fi
+	if [[ $build_ui == true ]]; then
+		cd ./ui || exit
+		printf "Building UI..."
+		if [[ ! -d ./node_modules ]]; then
+			npm install &>/dev/null
+		fi
+		export VITE_APP_BUILD_TAG="DEV-BUILD"
+		export VITE_BUILD=true
 
-  if [[ -z "$CONFIG_NAME" ]]; then
-    export CONFIG_NAME=DEBUG-CORE
-  fi
+		if ! npm run build &>../build/logs/ui-build.log; then
+			printf " FAILED\n"
+			cat ../build/logs/ui-build.log
+			echo "Aborting Weblens startup. Ensure \`npm run build\` completes successfully before starting Weblens."
+			exit 1
+		else
+			printf " DONE\n"
+		fi
 
-  APP_ROOT=$(pwd) ./build/bin/weblens
+		cd ..
+	fi
 
-  if [[ $restart == false ]]; then
-    break
-  fi
-  clear
+	printf "Building Weblens binary..."
+	rm -f ./build/bin/weblens
+
+	export GORACE="halt_on_error=1"
+	export CGO_CFLAGS_ALLOW='-Xpreprocessor'
+	go build -gcflags="all=-N -l" -race -o ./build/bin/weblens ./cmd/weblens/main.go &>./build/logs/weblens-build.log
+
+	if [[ ! -e ./build/bin/weblens ]]; then
+		printf " FAILED\n"
+		cat ./build/logs/weblens-build.log
+		echo "Failed to build Weblens, exiting..."
+		exit 1
+	fi
+	printf " DONE\n"
+
+	pkill -f exiftool
+
+	if [[ $detach == true ]]; then
+		printf "Starting Weblens and detaching..."
+		APP_ROOT="$(pwd)" CONFIG_NAME="$config_name" nohup ./build/bin/weblens &>"$log_file" &
+		weblens_pid=$!
+		echo "$weblens_pid" >./build/logs/weblens.pid
+		printf " RUNNING\n"
+		exit 0
+	fi
+
+	if [[ -n "$log_file" ]]; then
+		echo "Logging from now on to $log_file"
+		exec &>"$log_file" # Redirect both stdout and stderr to the log file
+	fi
+	APP_ROOT=$(pwd) CONFIG_NAME=$config_name ./build/bin/weblens
+	exit=$?
+
+	if [[ $restart != true ]]; then
+		break
+	fi
+
+	if [[ $exit != 0 ]] && [[ $exit != 137 ]]; then
+		echo "Got exit status $exit, exiting..."
+		exit 1
+	fi
+	clear
 
 done
-
diff --git a/scripts/testWeblens b/scripts/testWeblens
--- a/scripts/testWeblens
+++ b/scripts/testWeblens
@@ -5,32 +5,221 @@ if [[ ! -e ./ui ]]; then
   exit 1
 fi
 
-if [[ ! -e ./ui/dist/index.html ]]; then
-  cd ui
-  export VITE_APP_BUILD_TAG=test
-  export VITE_BUILD=true
-  npm install
-  npm run build
-  cd ..
-fi
+mkdir -p build/logs
 
-if [[ "$REMOTE_TESTS" == "true" ]]; then
-  if ! source ./scripts/setupRemoteTests; then
-    echo "ERR Failed to setup remote tests, not running tests"
+tail_pid=-1
+tail_file=""
+do_tail() {
+  tail_file="$1"
+  if [[ $show_logs == true ]]; then
+    printf "\n"
+    : >"$1"
+    tail -f "$1" &
+    tail_pid=$!
+  else
+    printf " "
+  fi
+}
+
+stop_tail() {
+  if [[ $tail_pid -ne -1 ]]; then
+    kill $tail_pid &>/dev/null
+    wait $tail_pid 2>/dev/null
+    tail_pid=-1
+    tail_file=""
+  fi
+}
+
+failed=false
+RED='\033[0;31m'
+GREEN='\033[0;32m'
+NC='\033[0m' # No Color
+show_fail() {
+  failed=true
+  printf "%bFAIL%b\n" "${RED}" "${NC}"
+  if [[ $show_logs != true ]]; then
+    cat "$tail_file"
+    printf "%bFAIL%b\n" "${RED}" "${NC}"
+  fi
+  stop_tail
+}
+show_pass() {
+  stop_tail
+  printf "%bPASS%b\n" "${GREEN}" "${NC}"
+}
+
+trap 'kill $tail_pid &>/dev/null' EXIT
+
+usage="
+Usage: $0 [OPTIONS]
+
+This script consolidates and handles various Weblens tests. 
+
+Options:
+  --backend               
+      Enable basic backend tests
+
+  -r, --remote-tests      
+      Enable remote (end-to-end) tests for the backend 
+      (sets --backend)
+
+  --ui                    
+      Enable UI tests
+
+  --coverage              
+      Generate and display go test coverage report
+
+  -a, --all               
+      Run both backend (includes remote) and UI tests 
+      (sets --remote-tests and --ui)
+
+  -l, --show-logs         
+      Display logs during the test run (logs are also saved to ./build/logs and are printed on test failure reglardless of this flag)
+"
+
+backend_tests=false
+remote_tests=false
+show_logs=false
+ui_tests=false
+coverage=false
+loop=false
+
+while [ "${1:-}" != "" ]; do
+  case "$1" in
+  "-a" | "--all")
+    backend_tests=true
+    remote_tests=true
+    ui_tests=true
+    ;;
+  "--backend")
+    backend_tests=true
+    ;;
+  "-r" | "--remote-tests")
+    backend_tests=true
+    remote_tests=true
+    ;;
+  "--target")
+    shift
+    target=$1
+    ;;
+  "-l" | "--show-logs")
+    show_logs=true
+    ;;
+  "--coverage")
+    coverage=true
+    ;;
+  "--ui")
+    ui_tests=true
+    ;;
+  "--loop")
+    loop=true
+    ;;
+  "-h" | "--help")
+    echo "$usage"
+    exit 0
+    ;;
+  *)
+    "Unknown argument: $1"
+    echo "$usage"
+    exit 1
+    ;;
+  esac
+  shift
+done
+
+while true; do
+  if [[ $REMOTE_TESTS == true ]]; then
+    remote_tests=true
+    backend_tests=true
+  fi
+
+  if [[ $ui_tests != true ]] && [[ $backend_tests != true ]]; then
+    echo "No tests selected..."
+    echo "$usage"
     exit 1
   fi
-fi
 
-target=$1
-if [[ -z "$target" ]]; then
-  target="./..."
-fi
+  if [[ ! -e ./ui/dist/index.html ]] || [[ ! -d ./ui/node_modules ]]; then
+    cd ui || exit
+    export VITE_APP_BUILD_TAG=test
+    export VITE_BUILD=true
+    # npm install
+    npm run build
+    cd .. || exit
+  fi
 
-# if [[ "$REMOTE_TESTS" == "true" ]]; then
-#   APP_ROOT=$PWD CONFIG_PATH=$PWD/config CONFIG_NAME=TEST go test -v $target
-# else
-# fi
-(set -o pipefail; APP_ROOT=$PWD CONFIG_PATH=$PWD/config CONFIG_NAME=TEST go test -v $target | grep -v -e CONT -e PAUSE | grep --color=always -e "^" -e "FAIL" | GREP_COLOR="1;32" grep --color=always -e "^" -e "PASS")
+  if [[ $ui_tests == true ]]; then
+    printf "Running UI linter ..."
+    cd ui || exit
+    do_tail ../build/logs/ui-lint.log
+    if ! npx eslint . &>../build/logs/ui-lint.log; then
+      show_fail
+    else
+      show_pass
+    fi
+    cd .. || exit
+  fi
 
+  if [[ $remote_tests == true ]]; then
+    export REMOTE_TESTS=true
 
+    printf "Setting up remote tests ..."
+    do_tail ./build/logs/remote-setup.log
+    if ! source ./scripts/setupRemoteTests &>./build/logs/remote-setup.log; then
+      show_fail
+      printf "%bERR Failed to setup remote target, not running tests%b\n" "${RED}" "${NC}"
+      exit 1
+    fi
+    stop_tail
+    echo "Done"
+  fi
 
+  if [[ $backend_tests == true ]]; then
+    mongosh --eval "use weblens-test" --eval "db.dropDatabase()" >/dev/null
+    mongosh --eval "use weblens-core-test" --eval "db.dropDatabase()" >/dev/null
+    mongosh --eval "use weblens-backup-test" --eval "db.dropDatabase()" >/dev/null
+
+    if [[ -z "$target" ]]; then
+      target="./..."
+    else
+      echo "Using target: $target"
+    fi
+    printf "Running backend tests ..."
+    do_tail ./build/logs/backend-test.log
+
+    export CGO_CFLAGS_ALLOW='-Xpreprocessor'
+    if ! (
+      set -o pipefail
+      APP_ROOT=$PWD CONFIG_PATH=$PWD/config CONFIG_NAME=TEST go test -coverprofile ./build/logs/cover_raw.out -v "$target" &>./build/logs/backend-test.log
+    ); then
+      show_fail
+    else
+      if [[ $coverage == true ]]; then
+        grep -v -e internal -e models -e http -e mock ./build/logs/cover_raw.out >./build/logs/cover.out
+        rm ./build/logs/cover_raw.out
+      fi
+      show_pass
+    fi
+  fi
+
+  weblens_pid=$(cat ./build/logs/weblens.pid 2>/dev/null)
+
+  if [[ $remote_tests == true ]] && [[ -n $weblens_pid ]]; then
+    echo "Killing test weblens instance (PID: $weblens_pid)"
+    kill "$weblens_pid"
+  fi
+
+  if [[ $failed == true ]]; then
+    exit 1
+  fi
+
+  if [[ $coverage == true ]]; then
+    go tool cover -html=./build/logs/cover.out
+  fi
+
+  if [[ $loop != true ]]; then
+    exit 0
+  else
+    go clean -testcache
+  fi
+done
