Fix test

diff --git a/scripts/testWeblens b/scripts/testWeblens
--- a/scripts/testWeblens
+++ b/scripts/testWeblens
@@ -1,4 +1,6 @@
 #!/bin/bash
+set -o pipefail
+
 usage="Usage: $0 [-n|--native [package_target]]"
 
 run_native_tests() {
@@ -34,53 +36,23 @@ done
 
 arch=$(uname -m)
 
+docker network create weblens-net >/dev/null 2>&1
+docker volume rm weblens-test-mongo >/dev/null 2>&1
+
+docker stop weblens-test-mongo >/dev/null 2>&1
+docker rm weblens-test-mongo >/dev/null 2>&1
+./scripts/start-mongo.sh "weblens-test-mongo" || exit 1
+
 if ! docker build -t ethrous/weblens-test --build-arg ARCHITECTURE="$arch" --file ./docker/AlpineTester.Dockerfile .; then
     echo "Failed to build Docker image, exiting..."
     exit 1
 fi
 
-docker network create weblens-net >/dev/null 2>&1
-docker stop weblens-test-mongo >/dev/null 2>&1
-docker rm weblens-test-mongo >/dev/null 2>&1
-rm -rf ./build/fs/test-mongo-container/db
-
-echo "Starting MongoDB container..."
-docker run \
-    -d \
-    --name weblens-test-mongo \
-    --network weblens-net \
-    -v ./build/fs/test-mongo-container/db:/data/db \
-    mongo \
-    mongod --replSet rs0
-
-echo "MongoDB container started, waiting for it to be ready..."
-
-retries=0
-while [ $retries -lt 10 ]; do
-    retries=$((retries + 1))
-    if ! docker exec weblens-test-mongo mongosh --eval "rs.initiate({
-			_id: 'rs0',
-			members: [
-			{ _id: 0, host: 'weblens-test-mongo' }
-			]
-		})" 1>/dev/null; then
-        if ! docker ps | grep weblens-test-mongo; then
-            echo "MongoDB container is not running, exiting..."
-            docker logs weblens-test-mongo
-            exit 1
-        fi
-
-        echo "Waiting for MongoDB to be ready..."
-
-        sleep 1
-    else
-        break
-    fi
-done
-
-echo "MongoDB is ready, starting test container..."
-
 rm -rf ./build/fs/test-container
-docker run --rm --platform="linux/$arch" --network=weblens-net -v ./build/fs/test-container/data:/data -v ./build/fs/test-container/cache:/cache -v ./build/cache/test/go/pkg:/go/pkg/mod -v ./build/cache/test/go/build:/tmp/go-cache -v ./build/cover:/cover ethrous/weblens-test -n "${tests}"
 
-exit $?
+if ! docker run --rm --platform="linux/$arch" --network weblens-net -v ./build/fs/test-container/data:/data -v ./build/fs/test-container/cache:/cache -v ./build/cache/test/go/pkg:/go/pkg/mod -v ./build/cache/test/go/build:/tmp/go-cache -v ./build/cover:/cover -e WEBLENS_MONGODB_URI="mongodb://weblens-test-mongo:27017/?replicaSet=rs0" ethrous/weblens-test -n "${tests}"; then
+    echo "Tests failed, exiting..."
+    exit 1
+fi
+
+exit 0
