Fix linter errors and test failures

diff --git a/scripts/testWeblens b/scripts/testWeblens
--- a/scripts/testWeblens
+++ b/scripts/testWeblens
@@ -4,8 +4,6 @@ set -euo pipefail
 usage="Usage: $0 [-n|--native [package_target]]"
 
 run_native_tests() {
-    cd /src
-
     pushd ./weblens-vue/weblens-nuxt
     echo "Installing UI Dependencies..."
     pnpm install >/dev/null 2>&1
@@ -23,21 +21,49 @@ run_native_tests() {
     touch /tmp/weblens.env
     export WEBLENS_ENV_PATH=/tmp/weblens.env
     export WEBLENS_DO_CACHE=false
+    export WEBLENS_MONGODB_URI=${WEBLENS_MONGODB_URI:-"mongodb://127.0.0.1:27018/?replicaSet=rs0&directConnection=true"}
 
-    echo "Running tests with target: $target"
+    echo "Running tests with mongo [$WEBLENS_MONGODB_URI] and test target: [$target]"
     # /usr/local/go/bin/go test -v -cover -race -coverprofile=/cover/coverage.out "$target" | grep -v -e "=== RUN" -e "=== PAUSE" -e "--- PASS"
-    go test -v -race "$target"
+    go test -v -cover -race -coverprofile=_build/cover/coverage.out "$target" | grep -v -e "=== RUN" -e "=== PAUSE" -e "--- PASS"
     exit $?
+}
+
+run_container_tests() {
+    sudo docker network create weblens-net >/dev/null 2>&1 || true
+    sudo docker volume rm weblens-test-mongo >/dev/null 2>&1 || true
+
+    sudo docker stop weblens-test-mongo >/dev/null 2>&1 || true
+    sudo docker rm weblens-test-mongo >/dev/null 2>&1 || true
+    ./scripts/start-mongo.sh "weblens-test-mongo"
+
+    rm -rf ./_build/fs/test-container
+
+    if ! sudo docker run --rm --platform="linux/amd64" \
+        --network weblens-net \
+        -v ./_build/fs/test-container/data:/data \
+        -v ./_build/fs/test-container/cache:/cache \
+        -v ./_build/cache/test/go/build:/tmp/go-cache \
+        -v ./_build/cover:/cover \
+        -v ./:/src \
+        -v /src/weblens-vue/weblens-nuxt/node_modules \
+        -v /src/build \
+        -e WEBLENS_MONGODB_URI="mongodb://weblens-test-mongo:27017/?replicaSet=rs0" \
+        ethrous/weblens-roux":$baseVersion" /src/scripts/testWeblens "${tests}"; then
+        echo "Tests failed, exiting..."
+        exit 1
+    fi
+
 }
 
 tests=""
 baseVersion="v0"
+containerize=false
 
 while [ "${1:-}" != "" ]; do
     case "$1" in
-    "-n" | "--native")
-        shift
-        run_native_tests "${1:-}"
+    "-c" | "--containerize")
+        containerize=true
         ;;
     "-b" | "--base-version")
         shift
@@ -54,28 +80,8 @@ while [ "${1:-}" != "" ]; do
     shift
 done
 
-sudo docker network create weblens-net >/dev/null 2>&1 || true
-sudo docker volume rm weblens-test-mongo >/dev/null 2>&1 || true
-
-sudo docker stop weblens-test-mongo >/dev/null 2>&1 || true
-sudo docker rm weblens-test-mongo >/dev/null 2>&1 || true
-./scripts/start-mongo.sh "weblens-test-mongo"
-
-rm -rf ./_build/fs/test-container
-
-if ! sudo docker run --rm --platform="linux/amd64" \
-    --network weblens-net \
-    -v ./_build/fs/test-container/data:/data \
-    -v ./_build/fs/test-container/cache:/cache \
-    -v ./_build/cache/test/go/build:/tmp/go-cache \
-    -v ./_build/cover:/cover \
-    -v ./:/src \
-    -v /src/weblens-vue/weblens-nuxt/node_modules \
-    -v /src/build \
-    -e WEBLENS_MONGODB_URI="mongodb://weblens-test-mongo:27017/?replicaSet=rs0" \
-    ethrous/weblens-roux":$baseVersion" /src/scripts/testWeblens -n "${tests}"; then
-    echo "Tests failed, exiting..."
-    exit 1
+if [ "$containerize" = false ]; then
+    run_native_tests "${tests}"
+else
+    run_container_tests
 fi
-
-exit 0
